      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm' # キャッシュを有効化して帯域を節約

      - name: Install dependencies
        run: npm install  # ci から install に変更

      - name: Build
        run: npm run build:demo

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist  # viteのデフォルト出力先に合わせる（設定済みならそのままでOK）
          keep_files: false
